"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from .countries import (
    country_al,
    country_at,
    country_ba,
    country_be,
    country_bg,
    country_by,
    country_ch,
    country_cz,
    country_de,
    country_dk,
    country_ee,
    country_es,
    country_fi,
    country_fo,
    country_fr,
    country_gb,
    country_gg,
    country_gi,
    country_gr,
    country_hr,
    country_hu,
    country_ie,
    country_im,
    country_is,
    country_it,
    country_je,
    country_lt,
    country_lu,
    country_lv,
    country_md,
    country_me,
    country_mk,
    country_mt,
    country_nl,
    country_no,
    country_pl,
    country_pt,
    country_ro,
    country_rs,
    country_ru,
    country_se,
    country_si,
    country_sk,
    country_ua,
    country_xk,
)

AIRPORTS = (
    country_al.AIRPORTS
    | country_at.AIRPORTS
    | country_ba.AIRPORTS
    | country_be.AIRPORTS
    | country_bg.AIRPORTS
    | country_by.AIRPORTS
    | country_ch.AIRPORTS
    | country_cz.AIRPORTS
    | country_de.AIRPORTS
    | country_dk.AIRPORTS
    | country_ee.AIRPORTS
    | country_es.AIRPORTS
    | country_fi.AIRPORTS
    | country_fo.AIRPORTS
    | country_fr.AIRPORTS
    | country_gb.AIRPORTS
    | country_gg.AIRPORTS
    | country_gi.AIRPORTS
    | country_gr.AIRPORTS
    | country_hr.AIRPORTS
    | country_hu.AIRPORTS
    | country_ie.AIRPORTS
    | country_im.AIRPORTS
    | country_is.AIRPORTS
    | country_it.AIRPORTS
    | country_je.AIRPORTS
    | country_lt.AIRPORTS
    | country_lu.AIRPORTS
    | country_lv.AIRPORTS
    | country_md.AIRPORTS
    | country_me.AIRPORTS
    | country_mk.AIRPORTS
    | country_mt.AIRPORTS
    | country_nl.AIRPORTS
    | country_no.AIRPORTS
    | country_pl.AIRPORTS
    | country_pt.AIRPORTS
    | country_ro.AIRPORTS
    | country_rs.AIRPORTS
    | country_ru.AIRPORTS
    | country_se.AIRPORTS
    | country_si.AIRPORTS
    | country_sk.AIRPORTS
    | country_ua.AIRPORTS
    | country_xk.AIRPORTS
)
