"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LZIB": Airport(
        icao="LZIB",
        country="SK",
        name="M. R. Štefánik Airport",
        latitude=48.1702,
        longitude=17.2127,
        has_metar=True,
        has_taf=True,
        fir_icao="LZBB",
    ),
    "LZKZ": Airport(
        icao="LZKZ",
        country="SK",
        name="Košice International Airport",
        latitude=48.663101,
        longitude=21.2411,
        has_metar=True,
        has_taf=True,
        fir_icao="LZBB",
    ),
    "LZPP": Airport(
        icao="LZPP",
        country="SK",
        name="Piešťany Airport",
        latitude=48.62519836425781,
        longitude=17.828399658203125,
        has_metar=True,
        has_taf=True,
        fir_icao="LZBB",
    ),
    "LZSL": Airport(
        icao="LZSL",
        country="SK",
        name="Sliač Airport",
        latitude=48.63779830932617,
        longitude=19.13409996032715,
        has_metar=True,
        has_taf=True,
        fir_icao="LZBB",
    ),
    "LZTT": Airport(
        icao="LZTT",
        country="SK",
        name="Poprad-Tatry Airport",
        latitude=49.070994,
        longitude=20.241394,
        has_metar=True,
        has_taf=True,
        fir_icao="LZBB",
    ),
    "LZZI": Airport(
        icao="LZZI",
        country="SK",
        name="Žilina-Dolný Hričov Airport",
        latitude=49.233292,
        longitude=18.613386,
        has_metar=True,
        has_taf=True,
        fir_icao="LZBB",
    ),
}
