"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LBBG": Airport(
        icao="LBBG",
        country="BG",
        name="Burgas Airport",
        latitude=42.569917,
        longitude=27.515173,
        has_metar=True,
        has_taf=True,
        fir_icao="LBSR",
    ),
    "LBGO": Airport(
        icao="LBGO",
        country="BG",
        name="Gorna Oryahovitsa Airport",
        latitude=43.151402,
        longitude=25.7129,
        has_metar=True,
        has_taf=True,
        fir_icao="LBSR",
    ),
    "LBPD": Airport(
        icao="LBPD",
        country="BG",
        name="Plovdiv International Airport",
        latitude=42.067799,
        longitude=24.8508,
        has_metar=True,
        has_taf=True,
        fir_icao="LBSR",
    ),
    "LBPG": Airport(
        icao="LBPG",
        country="BG",
        name="Graf Ignatievo Air Base",
        latitude=42.290401,
        longitude=24.714001,
        has_metar=True,
        has_taf=True,
        fir_icao="LBSR",
    ),
    "LBPL": Airport(
        icao="LBPL",
        country="BG",
        name="Dolna Mitropoliya Air Base",
        latitude=43.451771,
        longitude=24.502423,
        has_metar=True,
        has_taf=False,
        fir_icao="LBSR",
    ),
    "LBSF": Airport(
        icao="LBSF",
        country="BG",
        name="Sofia Airport",
        latitude=42.696357,
        longitude=23.417671,
        has_metar=True,
        has_taf=True,
        fir_icao="LBSR",
    ),
    "LBWB": Airport(
        icao="LBWB",
        country="BG",
        name="Balchik Airfield",
        latitude=43.423801,
        longitude=28.181299,
        has_metar=True,
        has_taf=False,
        fir_icao="LBSR",
    ),
    "LBWN": Airport(
        icao="LBWN",
        country="BG",
        name="Varna Airport",
        latitude=43.232101,
        longitude=27.8251,
        has_metar=True,
        has_taf=True,
        fir_icao="LBSR",
    ),
}
