"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LOAN": Airport(
        icao="LOAN",
        country="AT",
        name="Wiener Neustadt East Airport",
        latitude=47.8433,
        longitude=16.260099,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOWG": Airport(
        icao="LOWG",
        country="AT",
        name="Graz Airport",
        latitude=46.9911,
        longitude=15.4396,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOWI": Airport(
        icao="LOWI",
        country="AT",
        name="Innsbruck Airport",
        latitude=47.260201,
        longitude=11.344,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOWK": Airport(
        icao="LOWK",
        country="AT",
        name="Klagenfurt Airport",
        latitude=46.642502,
        longitude=14.3377,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOWL": Airport(
        icao="LOWL",
        country="AT",
        name="Linz-Hörsching Airport",
        latitude=48.235362,
        longitude=14.188128,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOWS": Airport(
        icao="LOWS",
        country="AT",
        name="Salzburg Airport",
        latitude=47.793301,
        longitude=13.0043,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOWW": Airport(
        icao="LOWW",
        country="AT",
        name="Vienna International Airport",
        latitude=48.110298,
        longitude=16.5697,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
    "LOXZ": Airport(
        icao="LOXZ",
        country="AT",
        name="Hinterstoisser Air Base",
        latitude=47.202801,
        longitude=14.7442,
        has_metar=True,
        has_taf=True,
        fir_icao="LOVV",
    ),
}
