"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EGJA": Airport(
        icao="EGJA",
        country="GG",
        name="Alderney Airport",
        latitude=49.706104,
        longitude=-2.21472,
        has_metar=True,
        has_taf=True,
        fir_icao="LFRR",
    ),
    "EGJB": Airport(
        icao="EGJB",
        country="GG",
        name="Guernsey Airport",
        latitude=49.435001,
        longitude=-2.60197,
        has_metar=True,
        has_taf=True,
        fir_icao="LFRR",
    ),
}
