"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "BIAR": Airport(
        icao="BIAR",
        country="IS",
        name="Akureyri International Airport",
        latitude=65.656573,
        longitude=-18.072018,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIBD": Airport(
        icao="BIBD",
        country="IS",
        name="Bildudalur Airport",
        latitude=65.641296,
        longitude=-23.5462,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIEG": Airport(
        icao="BIEG",
        country="IS",
        name="Egilsstaðir Airport",
        latitude=65.2833023071289,
        longitude=-14.401399612426758,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIGR": Airport(
        icao="BIGR",
        country="IS",
        name="Grímsey Airport",
        latitude=66.5458,
        longitude=-18.0173,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIHN": Airport(
        icao="BIHN",
        country="IS",
        name="Hornafjörður Airport",
        latitude=64.295601,
        longitude=-15.2272,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIHU": Airport(
        icao="BIHU",
        country="IS",
        name="Húsavík Airport",
        latitude=65.952301,
        longitude=-17.426001,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIIS": Airport(
        icao="BIIS",
        country="IS",
        name="Ísafjörður Airport",
        latitude=66.058098,
        longitude=-23.1353,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIKF": Airport(
        icao="BIKF",
        country="IS",
        name="Keflavik International Airport",
        latitude=63.985001,
        longitude=-22.6056,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIRK": Airport(
        icao="BIRK",
        country="IS",
        name="Reykjavík Domestic Airport",
        latitude=64.128732,
        longitude=-21.93759,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIVM": Airport(
        icao="BIVM",
        country="IS",
        name="Vestmannaeyjar Airport",
        latitude=63.42430114746094,
        longitude=-20.278900146484375,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "BIVO": Airport(
        icao="BIVO",
        country="IS",
        name="Vopnafjörður Airport",
        latitude=65.720596,
        longitude=-14.8506,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
}
