"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LWOH": Airport(
        icao="LWOH",
        country="MK",
        name="Ohrid St. Paul the Apostle Airport",
        latitude=41.18,
        longitude=20.7423,
        has_metar=True,
        has_taf=True,
        fir_icao="LWSS",
    ),
    "LWSK": Airport(
        icao="LWSK",
        country="MK",
        name="Skopje International Airport",
        latitude=41.958087,
        longitude=21.622581,
        has_metar=True,
        has_taf=True,
        fir_icao="LWSS",
    ),
}
