"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LUBL": Airport(
        icao="LUBL",
        country="MD",
        name="Bălți-Leadoveni International Airport",
        latitude=47.837666,
        longitude=27.781108,
        has_metar=True,
        has_taf=True,
        fir_icao="LUUU",
    ),
    "LUBM": Airport(
        icao="LUBM",
        country="MD",
        name="Mărculești Air Base",
        latitude=47.862701,
        longitude=28.212799,
        has_metar=True,
        has_taf=True,
        fir_icao="LUUU",
    ),
    "LUCH": Airport(
        icao="LUCH",
        country="MD",
        name="Cahul International Airport",
        latitude=45.8438,
        longitude=28.2637,
        has_metar=True,
        has_taf=True,
        fir_icao="LUUU",
    ),
    "LUKK": Airport(
        icao="LUKK",
        country="MD",
        name="Chişinău International Airport",
        latitude=46.92774,
        longitude=28.931704,
        has_metar=True,
        has_taf=True,
        fir_icao="LUUU",
    ),
}
