"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EBAW": Airport(
        icao="EBAW",
        country="BE",
        name="Antwerp International Airport (Deurne)",
        latitude=51.190667,
        longitude=4.463153,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBBE": Airport(
        icao="EBBE",
        country="BE",
        name="Beauvechain Air Base",
        latitude=50.758598,
        longitude=4.76833,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBBL": Airport(
        icao="EBBL",
        country="BE",
        name="Kleine Brogel Air Base",
        latitude=51.168301,
        longitude=5.47,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBBR": Airport(
        icao="EBBR",
        country="BE",
        name="Brussels Airport",
        latitude=50.901402,
        longitude=4.48444,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBCI": Airport(
        icao="EBCI",
        country="BE",
        name="Brussels South Charleroi Airport",
        latitude=50.461963,
        longitude=4.459562,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBCV": Airport(
        icao="EBCV",
        country="BE",
        name="Chièvres Air Base",
        latitude=50.575802,
        longitude=3.831,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBFN": Airport(
        icao="EBFN",
        country="BE",
        name="Koksijde Air Base",
        latitude=51.090302,
        longitude=2.65278,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBFS": Airport(
        icao="EBFS",
        country="BE",
        name="Florennes Air Base",
        latitude=50.2433013916,
        longitude=4.64583015442,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBLG": Airport(
        icao="EBLG",
        country="BE",
        name="Liège Airport",
        latitude=50.638574,
        longitude=5.443897,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
    "EBOS": Airport(
        icao="EBOS",
        country="BE",
        name="Ostend-Bruges International Airport",
        latitude=51.1998,
        longitude=2.874673,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
}
