"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EKVG": Airport(
        icao="EKVG",
        country="FO",
        name="Vágar Airport",
        latitude=62.063256,
        longitude=-7.275782,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
}
