"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "BKPR": Airport(
        icao="BKPR",
        country="XK",
        name="Priština Adem Jashari International Airport",
        latitude=42.5728,
        longitude=21.035801,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
}
