"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "UMBB": Airport(
        icao="UMBB",
        country="BY",
        name="Brest International Airport",
        latitude=52.108138,
        longitude=23.89676,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "UMGG": Airport(
        icao="UMGG",
        country="BY",
        name="Gomel Airport",
        latitude=52.527000427246094,
        longitude=31.016700744628906,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "UMII": Airport(
        icao="UMII",
        country="BY",
        name="Vitebsk Vostochny Airport",
        latitude=55.126499176025,
        longitude=30.349599838257,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "UMMG": Airport(
        icao="UMMG",
        country="BY",
        name="Hrodna Airport",
        latitude=53.602001,
        longitude=24.053801,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "UMMS": Airport(
        icao="UMMS",
        country="BY",
        name="Minsk National Airport",
        latitude=53.888071,
        longitude=28.039964,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
    "UMOO": Airport(
        icao="UMOO",
        country="BY",
        name="Mogilev Airport",
        latitude=53.954898834228516,
        longitude=30.09510040283203,
        has_metar=True,
        has_taf=True,
        fir_icao="",
    ),
}
