"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EGNS": Airport(
        icao="EGNS",
        country="IM",
        name="Isle of Man Airport",
        latitude=54.083081,
        longitude=-4.623871,
        has_metar=True,
        has_taf=True,
        fir_icao="EGTT",
    ),
}
