"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EGJJ": Airport(
        icao="EGJJ",
        country="JE",
        name="Jersey Airport",
        latitude=49.207901,
        longitude=-2.19551,
        has_metar=True,
        has_taf=True,
        fir_icao="LFRR",
    ),
}
