"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LHBP": Airport(
        icao="LHBP",
        country="HU",
        name="Budapest Liszt Ferenc International Airport",
        latitude=47.43018,
        longitude=19.262393,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
    "LHDC": Airport(
        icao="LHDC",
        country="HU",
        name="Debrecen International Airport",
        latitude=47.489469,
        longitude=21.616278,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
    "LHKE": Airport(
        icao="LHKE",
        country="HU",
        name="Kecskemét Air Base",
        latitude=46.9175,
        longitude=19.749201,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
    "LHPP": Airport(
        icao="LHPP",
        country="HU",
        name="Pécs-Pogány International Airport",
        latitude=45.988891,
        longitude=18.242044,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
    "LHPR": Airport(
        icao="LHPR",
        country="HU",
        name="Győr-Pér Airport",
        latitude=47.628436,
        longitude=17.804718,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
    "LHSM": Airport(
        icao="LHSM",
        country="HU",
        name="Hévíz–Balaton Airport",
        latitude=46.686391,
        longitude=17.159084,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
    "LHSN": Airport(
        icao="LHSN",
        country="HU",
        name="Szolnok Air Base",
        latitude=47.122897,
        longitude=20.2355,
        has_metar=True,
        has_taf=True,
        fir_icao="LHCC",
    ),
}
