"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EYKA": Airport(
        icao="EYKA",
        country="LT",
        name="Kaunas International Airport",
        latitude=54.963965,
        longitude=24.08582,
        has_metar=True,
        has_taf=True,
        fir_icao="EYVL",
    ),
    "EYPA": Airport(
        icao="EYPA",
        country="LT",
        name="Palanga International Airport",
        latitude=55.973202,
        longitude=21.093901,
        has_metar=True,
        has_taf=True,
        fir_icao="EYVL",
    ),
    "EYSA": Airport(
        icao="EYSA",
        country="LT",
        name="Šiauliai International Airport",
        latitude=55.89390182495117,
        longitude=23.395000457763672,
        has_metar=True,
        has_taf=True,
        fir_icao="EYVL",
    ),
    "EYVI": Airport(
        icao="EYVI",
        country="LT",
        name="Vilnius International Airport",
        latitude=54.634102,
        longitude=25.285801,
        has_metar=True,
        has_taf=True,
        fir_icao="EYVL",
    ),
}
