"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LYBE": Airport(
        icao="LYBE",
        country="RS",
        name="Belgrade Nikola Tesla Airport",
        latitude=44.818401,
        longitude=20.309099,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
    "LYBT": Airport(
        icao="LYBT",
        country="RS",
        name="Batajnica Air Base",
        latitude=44.935299,
        longitude=20.2575,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
    "LYKV": Airport(
        icao="LYKV",
        country="RS",
        name="Morava Airport",
        latitude=43.817519,
        longitude=20.586662,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
    "LYNI": Airport(
        icao="LYNI",
        country="RS",
        name="Niš Constantine the Great Airport",
        latitude=43.336538,
        longitude=21.856242,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
    "LYUZ": Airport(
        icao="LYUZ",
        country="RS",
        name="Ponikve Airport",
        latitude=43.898899,
        longitude=19.697701,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
}
