"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LMML": Airport(
        icao="LMML",
        country="MT",
        name="Malta International Airport",
        latitude=35.845932,
        longitude=14.491546,
        has_metar=True,
        has_taf=True,
        fir_icao="LMMM",
    ),
}
