"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EEEI": Airport(
        icao="EEEI",
        country="EE",
        name="Ämari Air Base",
        latitude=59.259599,
        longitude=24.204799,
        has_metar=True,
        has_taf=True,
        fir_icao="EETT",
    ),
    "EEKA": Airport(
        icao="EEKA",
        country="EE",
        name="Kärdla Airport",
        latitude=58.99079895019531,
        longitude=22.830699920654297,
        has_metar=True,
        has_taf=True,
        fir_icao="EETT",
    ),
    "EEKE": Airport(
        icao="EEKE",
        country="EE",
        name="Kuressaare Airport",
        latitude=58.22990036010742,
        longitude=22.50950050354004,
        has_metar=True,
        has_taf=True,
        fir_icao="EETT",
    ),
    "EEPU": Airport(
        icao="EEPU",
        country="EE",
        name="Pärnu Airport",
        latitude=58.41899871826172,
        longitude=24.47279930114746,
        has_metar=True,
        has_taf=True,
        fir_icao="EETT",
    ),
    "EETN": Airport(
        icao="EETN",
        country="EE",
        name="Lennart Meri Tallinn Airport",
        latitude=59.413246,
        longitude=24.83264,
        has_metar=True,
        has_taf=True,
        fir_icao="EETT",
    ),
    "EETU": Airport(
        icao="EETU",
        country="EE",
        name="Tartu Airport",
        latitude=58.307438,
        longitude=26.686473,
        has_metar=True,
        has_taf=True,
        fir_icao="EETT",
    ),
}
