"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LDDU": Airport(
        icao="LDDU",
        country="HR",
        name="Dubrovnik Ruđer Bošković Airport",
        latitude=42.562247,
        longitude=18.265543,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDOS": Airport(
        icao="LDOS",
        country="HR",
        name="Osijek Airport",
        latitude=45.462355,
        longitude=18.811278,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDPL": Airport(
        icao="LDPL",
        country="HR",
        name="Pula Airport",
        latitude=44.893501,
        longitude=13.9222,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDRI": Airport(
        icao="LDRI",
        country="HR",
        name="Rijeka Airport",
        latitude=45.216376,
        longitude=14.57085,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDSB": Airport(
        icao="LDSB",
        country="HR",
        name="Brač Airport",
        latitude=43.284454,
        longitude=16.678362,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDSP": Airport(
        icao="LDSP",
        country="HR",
        name="Split Saint Jerome Airport",
        latitude=43.538898,
        longitude=16.298,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDZA": Airport(
        icao="LDZA",
        country="HR",
        name="Zagreb Franjo Tuđman International Airport",
        latitude=45.742901,
        longitude=16.0688,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
    "LDZD": Airport(
        icao="LDZD",
        country="HR",
        name="Zadar Airport",
        latitude=44.096986,
        longitude=15.353565,
        has_metar=True,
        has_taf=True,
        fir_icao="LDZO",
    ),
}
