"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "ELLX": Airport(
        icao="ELLX",
        country="LU",
        name="Luxembourg-Findel International Airport",
        latitude=49.626845,
        longitude=6.212134,
        has_metar=True,
        has_taf=True,
        fir_icao="EBBU",
    ),
}
