"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LAKU": Airport(
        icao="LAKU",
        country="AL",
        name="Kukës International Airport",
        latitude=42.035802,
        longitude=20.415955,
        has_metar=True,
        has_taf=True,
        fir_icao="LAAA",
    ),
    "LATI": Airport(
        icao="LATI",
        country="AL",
        name="Tirana International Airport Mother Teresa",
        latitude=41.4147,
        longitude=19.7206,
        has_metar=True,
        has_taf=True,
        fir_icao="LAAA",
    ),
}
