"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EICK": Airport(
        icao="EICK",
        country="IE",
        name="Cork International Airport",
        latitude=51.841301,
        longitude=-8.49111,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EIDL": Airport(
        icao="EIDL",
        country="IE",
        name="Donegal Airport",
        latitude=55.0442008972168,
        longitude=-8.340999603271484,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EIDW": Airport(
        icao="EIDW",
        country="IE",
        name="Dublin Airport",
        latitude=53.428713,
        longitude=-6.262121,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EIKN": Airport(
        icao="EIKN",
        country="IE",
        name="Ireland West Airport Knock",
        latitude=53.910439,
        longitude=-8.817002,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EIKY": Airport(
        icao="EIKY",
        country="IE",
        name="Kerry Airport",
        latitude=52.180901,
        longitude=-9.52378,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EIME": Airport(
        icao="EIME",
        country="IE",
        name="Casement Air Base",
        latitude=53.301700592,
        longitude=-6.451330184940001,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EINN": Airport(
        icao="EINN",
        country="IE",
        name="Shannon Airport",
        latitude=52.702,
        longitude=-8.92482,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EISG": Airport(
        icao="EISG",
        country="IE",
        name="Sligo Airport",
        latitude=54.280200958252,
        longitude=-8.5992097854614,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
    "EIWF": Airport(
        icao="EIWF",
        country="IE",
        name="Waterford Airport",
        latitude=52.187199,
        longitude=-7.08696,
        has_metar=True,
        has_taf=True,
        fir_icao="EISN",
    ),
}
