"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LYPG": Airport(
        icao="LYPG",
        country="ME",
        name="Podgorica Airport / Podgorica Golubovci Airbase",
        latitude=42.359402,
        longitude=19.2519,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
    "LYTV": Airport(
        icao="LYTV",
        country="ME",
        name="Tivat Airport",
        latitude=42.404701,
        longitude=18.723301,
        has_metar=True,
        has_taf=True,
        fir_icao="LYBA",
    ),
}
