"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LJCE": Airport(
        icao="LJCE",
        country="SI",
        name="Cerklje ob Krki Air Base",
        latitude=45.900002,
        longitude=15.5302,
        has_metar=True,
        has_taf=True,
        fir_icao="LJLA",
    ),
    "LJLJ": Airport(
        icao="LJLJ",
        country="SI",
        name="Ljubljana Jože Pučnik Airport",
        latitude=46.223701,
        longitude=14.4576,
        has_metar=True,
        has_taf=True,
        fir_icao="LJLA",
    ),
    "LJMB": Airport(
        icao="LJMB",
        country="SI",
        name="Maribor Edvard Rusjan Airport",
        latitude=46.4799,
        longitude=15.6861,
        has_metar=True,
        has_taf=True,
        fir_icao="LJLA",
    ),
    "LJPZ": Airport(
        icao="LJPZ",
        country="SI",
        name="Portorož Airport",
        latitude=45.47201,
        longitude=13.615951,
        has_metar=True,
        has_taf=True,
        fir_icao="LJLA",
    ),
}
