"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LXGB": Airport(
        icao="LXGB",
        country="GI",
        name="Gibraltar Airport",
        latitude=36.151679,
        longitude=-5.34978,
        has_metar=True,
        has_taf=True,
        fir_icao="LECM",
    ),
}
