"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "LQBK": Airport(
        icao="LQBK",
        country="BA",
        name="Banja Luka International Airport",
        latitude=44.941399,
        longitude=17.297501,
        has_metar=True,
        has_taf=True,
        fir_icao="LQSB",
    ),
    "LQMO": Airport(
        icao="LQMO",
        country="BA",
        name="Mostar International Airport",
        latitude=43.282489,
        longitude=17.846101,
        has_metar=True,
        has_taf=True,
        fir_icao="LQSB",
    ),
    "LQSA": Airport(
        icao="LQSA",
        country="BA",
        name="Sarajevo International Airport",
        latitude=43.8246,
        longitude=18.331499,
        has_metar=True,
        has_taf=True,
        fir_icao="LQSB",
    ),
    "LQTZ": Airport(
        icao="LQTZ",
        country="BA",
        name="Tuzla International Airport",
        latitude=44.459858,
        longitude=18.723627,
        has_metar=True,
        has_taf=True,
        fir_icao="LQSB",
    ),
}
