"""AUTO-GENERATED FILE.

Do not edit manually.

Generated by scripts/generate_airports.py.
"""

from __future__ import annotations

from ..models import Airport

AIRPORTS: dict[str, Airport] = {
    "EVLA": Airport(
        icao="EVLA",
        country="LV",
        name="Liepāja International Airport",
        latitude=56.517502,
        longitude=21.096901,
        has_metar=True,
        has_taf=True,
        fir_icao="EVRR",
    ),
    "EVRA": Airport(
        icao="EVRA",
        country="LV",
        name="Riga International Airport",
        latitude=56.920752,
        longitude=23.970711,
        has_metar=True,
        has_taf=True,
        fir_icao="EVRR",
    ),
}
